apiVersion: apps/v1
kind: Deployment
metadata:
  name: birxbackend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: birxbackend
  template:
    metadata:
      labels:
        app: birxbackend
    spec:
      containers:
        - name: birxbackend
          image: shahabuddinakhon/backendbirx:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: birxbackend-service
spec:
  selector:
    app: birxbackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
